/* Each family is a minimal identity. The engine rotates every member as the target. */
(function (root) {
  'use strict';

  const family = (id, name, keys, equalSpacing = false) => ({
    id,
    name,
    keys,
    ...(equalSpacing ? { equalSpacing: true } : {}),
  });

  const families = [
    family('parity-components', 'Stock, strike, and parity',
      ['parity:1', 'stock', 'strike:1']),
    family('put-call-parity', 'Put-call parity',
      ['call:1:1', 'put:1:1', 'stock', 'strike:1', 'rc:1']),
    family('parity-and-carry', 'Option difference from parity and r/c',
      ['call:1:1', 'put:1:1', 'parity:1', 'rc:1']),
    family('combo-options', 'Call and put in a combo',
      ['combo:1:1', 'call:1:1', 'put:1:1']),
    family('combo-parity-carry', 'Combo, parity, and r/c',
      ['combo:1:1', 'parity:1', 'rc:1']),

    family('straddle-combo-call', 'Straddle plus combo isolates the call',
      ['straddle:1:1', 'combo:1:1', 'call:1:1']),
    family('straddle-combo-put', 'Straddle minus combo isolates the put',
      ['straddle:1:1', 'combo:1:1', 'put:1:1']),
    family('straddle-call-parity', 'Straddle from the call side of parity',
      ['straddle:1:1', 'call:1:1', 'parity:1', 'rc:1']),
    family('straddle-put-parity', 'Straddle from the put side of parity',
      ['straddle:1:1', 'put:1:1', 'parity:1', 'rc:1']),

    family('buy-write-put-carry', 'B/W as put plus r/c',
      ['bw:1:1', 'put:1:1', 'rc:1']),
    family('buy-write-call-parity', 'B/W as call minus parity',
      ['bw:1:1', 'call:1:1', 'parity:1']),
    family('buy-write-stock-strike', 'Stock and strike inside B/W',
      ['bw:1:1', 'call:1:1', 'stock', 'strike:1']),
    family('put-stock-call-carry', 'P&S as call minus r/c',
      ['ps:1:1', 'call:1:1', 'rc:1']),
    family('put-stock-put-parity', 'P&S as put plus parity',
      ['ps:1:1', 'put:1:1', 'parity:1']),
    family('put-stock-stock-strike', 'Stock and strike inside P&S',
      ['ps:1:1', 'put:1:1', 'stock', 'strike:1']),
    family('buy-write-put-stock-straddle', 'B/W plus P&S makes a straddle',
      ['bw:1:1', 'ps:1:1', 'straddle:1:1']),
    family('buy-write-put-stock-difference', 'B/W minus P&S compares r/c and parity',
      ['bw:1:1', 'ps:1:1', 'rc:1', 'parity:1']),
    family('straddle-buy-write-call', 'B/W and call reconstruct the straddle',
      ['straddle:1:1', 'bw:1:1', 'call:1:1', 'rc:1']),
    family('straddle-put-stock-put', 'P&S and put reconstruct the straddle',
      ['straddle:1:1', 'ps:1:1', 'put:1:1', 'rc:1']),

    family('risky-option-legs', 'Signed risky option legs',
      ['risky:1:2:1', 'call:1:1', 'put:2:1']),
    family('strangle-option-legs', 'Strangle option legs',
      ['strangle:1:2:1', 'call:1:1', 'put:2:1']),
    family('strangle-risky-call', 'Strangle plus risky isolates the call',
      ['strangle:1:2:1', 'risky:1:2:1', 'call:1:1']),
    family('strangle-risky-put', 'Strangle minus risky isolates the put',
      ['strangle:1:2:1', 'risky:1:2:1', 'put:2:1']),
    family('risky-high-combo-put-vertical', 'Move the put leg of a high-strike combo',
      ['risky:1:2:1', 'combo:1:1', 'pv:1:2:1']),
    family('risky-low-combo-call-vertical', 'Move the call leg of a low-strike combo',
      ['risky:1:2:1', 'combo:2:1', 'cv:1:2:1']),
    family('strangle-high-straddle-put-vertical', 'Move the put leg of a high-strike straddle',
      ['strangle:1:2:1', 'straddle:1:1', 'pv:1:2:1']),
    family('strangle-low-straddle-call-vertical', 'Move the call leg of a low-strike straddle',
      ['strangle:1:2:1', 'straddle:2:1', 'cv:1:2:1']),

    family('box-strikes', 'Box and strike difference',
      ['box:1:2', 'strike:1', 'strike:2']),
    family('call-vertical-option-legs', 'Call vertical option legs',
      ['cv:1:2:1', 'call:1:1', 'call:2:1']),
    family('put-vertical-option-legs', 'Put vertical option legs',
      ['pv:1:2:1', 'put:1:1', 'put:2:1']),
    family('box-complementary-verticals', 'Complementary verticals make a box',
      ['box:1:2', 'cv:1:2:1', 'pv:1:2:1']),
    family('box-parity-difference', 'Parity change across strikes equals the box',
      ['box:1:2', 'parity:1', 'parity:2']),
    family('box-combo-difference', 'Combo change across strikes equals the box',
      ['box:1:2', 'combo:1:1', 'combo:2:1']),
    family('buy-write-put-vertical', 'B/W difference is a put vertical',
      ['bw:1:1', 'bw:2:1', 'pv:1:2:1']),
    family('put-stock-call-vertical', 'P&S difference is a call vertical',
      ['ps:1:1', 'ps:2:1', 'cv:1:2:1']),
    family('buy-write-complementary-call-vertical', 'B/W difference complements a call vertical',
      ['bw:1:1', 'bw:2:1', 'box:1:2', 'cv:1:2:1']),
    family('put-stock-complementary-put-vertical', 'P&S difference complements a put vertical',
      ['ps:1:1', 'ps:2:1', 'box:1:2', 'pv:1:2:1']),

    family('straddle-swap-legs', 'Buy the high-strike straddle and sell the low',
      ['swap:1:2:1', 'straddle:1:1', 'straddle:2:1']),
    family('straddle-swap-vertical-difference', 'Straddle swap is put vertical minus call vertical',
      ['swap:1:2:1', 'pv:1:2:1', 'cv:1:2:1']),
    family('straddle-swap-call-vertical-box', 'Straddle swap from the box and call vertical',
      ['swap:1:2:1', 'box:1:2', 'cv:1:2:1']),
    family('straddle-swap-put-vertical-box', 'Straddle swap from the box and put vertical',
      ['swap:1:2:1', 'box:1:2', 'pv:1:2:1']),

    family('call-time-spread-option-legs', 'Front call minus back call',
      ['ct:1:1:2', 'call:1:1', 'call:1:2']),
    family('put-time-spread-option-legs', 'Front put minus back put',
      ['pt:1:1:2', 'put:1:1', 'put:1:2']),
    family('time-spreads-carry-difference', 'Call and put time spreads differ by r/c',
      ['ct:1:1:2', 'pt:1:1:2', 'rc:1', 'rc:2']),
    family('time-spreads-jelly-roll', 'Jelly roll links call and put time spreads',
      ['ct:1:1:2', 'pt:1:1:2', 'jelly:1:1:2']),
    family('jelly-roll-carry', 'Jelly roll is earlier r/c minus later r/c',
      ['jelly:1:1:2', 'rc:1', 'rc:2']),
    family('jelly-roll-combos', 'Jelly roll is earlier combo minus later combo',
      ['jelly:1:1:2', 'combo:1:1', 'combo:1:2']),
    family('buy-write-call-time-spread', 'B/W change over time is the call time spread',
      ['ct:1:1:2', 'bw:1:1', 'bw:1:2']),
    family('put-stock-put-time-spread', 'P&S change over time is the put time spread',
      ['pt:1:1:2', 'ps:1:1', 'ps:1:2']),
    family('straddle-time-call-jelly', 'Straddle time change from calls and jelly roll',
      ['straddle:1:1', 'straddle:1:2', 'ct:1:1:2', 'jelly:1:1:2']),
    family('straddle-time-put-jelly', 'Straddle time change from puts and jelly roll',
      ['straddle:1:1', 'straddle:1:2', 'pt:1:1:2', 'jelly:1:1:2']),

    family('reversal-combo-parity', 'Reversal is combo minus parity',
      ['reversal:1', 'combo:1:1', 'parity:1']),
    family('conversion-parity-combo', 'Conversion is parity minus combo',
      ['conversion:1', 'parity:1', 'combo:1:1']),
    family('reversal-conversion', 'Reversal and conversion have opposite signs',
      ['reversal:1', 'conversion:1']),

    family('call-butterfly-option-legs', 'Call butterfly wings and double body',
      ['butterfly:1', 'call:1:1', 'call:2:1', 'call:3:1'], true),
    family('put-butterfly-option-legs', 'Put butterfly equals the call butterfly',
      ['butterfly:1', 'put:1:1', 'put:2:1', 'put:3:1'], true),
    family('butterfly-call-verticals', 'Butterfly is the difference of adjacent call verticals',
      ['butterfly:1', 'cv:1:2:1', 'cv:2:3:1'], true),
    family('butterfly-put-verticals', 'Butterfly is the difference of adjacent put verticals',
      ['butterfly:1', 'pv:1:2:1', 'pv:2:3:1'], true),
    family('butterfly-straddles', 'Straddle curvature is twice the butterfly',
      ['butterfly:1', 'straddle:1:1', 'straddle:2:1', 'straddle:3:1'], true),
    family('butterfly-buy-writes', 'B/W curvature preserves the butterfly',
      ['butterfly:1', 'bw:1:1', 'bw:2:1', 'bw:3:1'], true),
    family('butterfly-put-stocks', 'P&S curvature preserves the butterfly',
      ['butterfly:1', 'ps:1:1', 'ps:2:1', 'ps:3:1'], true),

    family('iron-fly-straddle-wings', 'Iron fly buys the middle straddle and sells the wings',
      ['iron:1', 'straddle:2:1', 'call:1:1', 'put:3:1'], true),
    family('iron-fly-strangle', 'Iron fly is middle straddle minus outer strangle',
      ['iron:1', 'straddle:2:1', 'strangle:1:3:1'], true),
    family('iron-fly-adjacent-verticals', 'Iron fly combines adjacent call and put verticals',
      ['iron:1', 'cv:1:2:1', 'pv:2:3:1'], true),
    family('iron-fly-box-butterfly', 'Iron fly and butterfly partition the strike gap',
      ['iron:1', 'box:1:2', 'butterfly:1'], true),
  ];

  root.PCP2MediumFamilies = families;
  if (typeof module !== 'undefined' && module.exports) module.exports = families;
})(typeof globalThis !== 'undefined' ? globalThis : this);
